### ISSUE TITLE
FAQ: Docker Compose instructions point to reinstallation of Docker Desktop

### ISSUE THREAD

**Issue by depasseg** [rancher-sandbox/docs.rancherdesktop.io#11]
On the FAQ page, under the loss of Docker Compose, the suggested fix links to the page to install Docker Compose, which in the case of Windows means that Docker Desktop appears to be needed to be re-installed.  If there was a way to use Docker Compose without reinstalling Docker Desktop, that would be good to link to.

**Comment by gunamata** [comment]
Updated the instructions with the PR #16 

Also, we are working on the docker-compose integration in this issue (https://github.com/rancher-sandbox/rancher-desktop/pull/1372 ), after which docker-compose comes bundled with Rancher Desktop.
