### ISSUE TITLE
TODO: Document where running `factory-reset` from the UI writes out the output from the `rdctl` CLI

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/docs.rancherdesktop.io#116]
Currently this gets written to `tmp()`/rdctl-stdout.txt` 

where on linux `tmp()` is usually `/tmp`,

on macOS it's given by `$TMPDIR`

and on Windows by `%TEMP%` or $env:TEMP` for powershell users.

The full path does get written to `background.log`, but unless the user is tailing this file when starting the `factory-reset` operation, this information will be lost when factory-reset deletes the log file.

The output is only necessary for post-mortem analysis when the factory-reset operation appears to fail.

**Comment by jandubois** [comment]
What is the use-case for this? Is this for internal use, or are users expected to locate it?

Doesn't `rdctl fctory-reset` notice when it appears to fail? Why wouldn't it write the location of the log file to stderr when this happens?

**Comment by jandubois** [comment]
If this fails when started from inside the UI, then maybe `rdctl` can still throw up some notification dialog, or open a file browser to the directory?

But I would like to understand first if this is really something we need to anticipate? I've found the hardened factory-reset code from the bats tests to be very effective and have not seen it fail (in the latest version).

**Comment by jandubois** [comment]
> On `macOS`, the moist straightforward way I can figure out how to show the temp dir is with these shell commands:

Isn't `$TMPDIR` already pointing to the right directory?

**Comment by ericpromislow** [comment]
Yes it does ... updated the main comment.

**Comment by jandubois** [comment]
> What is the use-case for this? Is this for internal use, or are users expected to locate it?

Still looking for an answer to this ^^^

Under which conditions should regular users find this information useful? If there aren't any, then we should not add this to the user documentation, but just a dev docs in the source repo.

**Comment by ericpromislow** [comment]
It's just a dev-doc issue then.

**Comment by ericpromislow** [comment]
Written up as a dev-doc in https://github.com/rancher-sandbox/rancher-desktop/pull/3703
