### ISSUE TITLE
Versioned docs should only include major.minor version numbers and exclude the patch

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/docs.rancherdesktop.io#117]
Right now the current docs version is `1.6.1`. This does not match the latest release, which is `1.6.2`. I don't think we want/need separate versions per patch release; patches only include fixes for regressions or security issues.

So I think the current docs should be version `1.6` right now, and the next version `1.7` etc.

**Comment by sunilarjun** [comment]
Change was implemented, closing issue, thank you
