### ISSUE TITLE
How to release real physics storage

### ISSUE THREAD

**Issue by 1989wanghang** [rancher-sandbox/docs.rancherdesktop.io#124]
"nerdctl rmi" or "nerdctl system prune --all" only remove the reference of unused data, release none on physics disk. The Avail storage value remains same on 'df -h' after run the above commands.
Where is the unused data? seems not in '/var/lib/nerdctl'.

my env: macos13, m1 version

**Comment by 1989wanghang** [comment]
"nerdctl rmi" or "nerdctl system prune --all" only remove the reference of unused data, release none on physics disk. The Avail storage value remains same on 'df -h' after run the above commands.
Where is the unused data? seems not in '/var/lib/nerdctl'.

my env: macos13, m1 version

**Comment by jandubois** [comment]
This is not implemented in the released versions.

In the upcoming 1.7 release, Rancher Desktop on macOS will release unused disk space back to the host when you terminate the application.

This will be exclusive to macOS and not work on Windows or Linux.

**Comment by jandubois** [comment]
I'm closing this issue, as it has already been implemented. Please re-open if it doesn't work for you (once 1.7 is released).
