### ISSUE TITLE
Document hidden /logs API

### ISSUE THREAD

**Issue by RichardoC** [rancher-sandbox/docs.rancherdesktop.io#136]
While experimenting with the following command, I spotted an API that's not present in upstream Kubernetes, which doesn't conform to their schema standards (it's non-json)

```bash 
$ kubectl  get --raw / | grep logs
    "/logs",

$ kubectl  get --raw /logs
<pre>
<a href="acpid.log">acpid.log</a>
<a href="buildkitd.log">buildkitd.log</a>
<a href="cloud-init-output.log">cloud-init-output.log</a>
<a href="containerd.log">containerd.log</a>
<a href="containers/">containers/</a>
<a href="dmesg">dmesg</a>
<a href="lima-init.log">lima-init.log</a>
<a href="messages">messages</a>
<a href="openresty/">openresty/</a>
<a href="pods/">pods/</a>
<a href="rancher-desktop-guestagent.log">rancher-desktop-guestagent.log</a>
<a href="wtmp">wtmp</a>
</pre>
```

This should be documented, and preferrably be json to conform to the other APIs exposed.

``` 
# Version info
$ rdctl  version
rdctl client version: 1.1.0, targeting server version: v0
# Rancher Desktop version 1.7.0 on Ubuntu 22.04.1 x64
$ kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.4", GitCommit:"95ee5ab382d64cfe6c28967f36b53970b8374491", GitTreeState:"clean", BuildDate:"2022-08-17T18:54:23Z", GoVersion:"go1.18.5", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.4
Server Version: version.Info{Major:"1", Minor:"24", GitVersion:"v1.24.8+k3s1", GitCommit:"648004e4faeaf9e8705386342e95ec9bd211c2b8", GitTreeState:"clean", BuildDate:"2022-11-18T18:29:47Z", GoVersion:"go1.18.8", Compiler:"gc", Platform:"linux/amd64"}
```

Thanks,

**Comment by RichardoC** [comment]
After some more investigation, it looks like k3s server is serving the contents of /var/logs on this path, though I can't find the code that's doing it

**Comment by mook-as** [comment]
As you found, this is a k3s thing and not a Rancher Desktop-specific thing. Please file this within their repository instead, thanks! (FWIW, I don't believe anybody on the RD team was aware of that endpoint.)

**Comment by brandond** [comment]
This is not a K3s thing. Are you sure it's not coming from RD?

**Comment by brandond** [comment]
You can start K3s with `--kube-apiserver-arg=enable-logs-handler=false` if you want to turn it off.

**Comment by RichardoC** [comment]
Thanks for the swift response and pointing me in the right direction! I'll raise it with Kubernetes upstream then since it's not listed in their API one pager https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.25/
