### ISSUE TITLE
Use cloud storage (ex: AWS S3) to store docs images instead of storing on GitHub repo

### ISSUE THREAD

**Issue by gunamata** [rancher-sandbox/docs.rancherdesktop.io#141]
**Why?** 

With the versioned docs rolled our from Rancher Desktop release 1.7.0, we need to maintain a set of images for every Rancher desktop minor release that goes out, and it increases the size of this repo as we do releases. 

So, The idea of this issue is to store images elsewhere so that docs engineers do not have to clone all the images of all versions all the time. Some potential approaches are:

- Use a cloud storage solution such as AWS S3
- Maintain the images in a separate GitHub repo and link to the images from docs using raw urls
- Maintain the images in a separate branch in this repo and link to the images from docs using raw urls

**Comment by nunix** [comment]
S3 is now being used for all the preferences and UI images.
We entered a "performance monitoring" phase and if conclusive, we'll store all images into S3.

This issue can/should stay open until then.
