### ISSUE TITLE
Document Traefik port bindings in installation guide on Linux

### ISSUE THREAD

**Issue by s0nea** [rancher-sandbox/docs.rancherdesktop.io#149]
Traefik is not accessible out of the box after a successful RD deployment on Linux. As mentioned in https://github.com/rancher-sandbox/rancher-desktop/issues/3916#issuecomment-1424630225 and https://github.com/rancher-sandbox/rancher-desktop/issues/1668#issuecomment-1064196699, the lower port bindings need to be allowed, first. This can be done by (`sudo` is required):

`sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80`

Because this command is only mandatory in Linux, it would be great if the installation guide could cover it, too.

**Comment by Nino-K** [comment]
We should also document port `443` since traefik also listens on that port.

**Comment by jandubois** [comment]
> We should also document port `443` since traefik also listens on that port.

Sure, but the command above makes all ports at 80 **and above** unprivileged. You cannot change the state of a single port; you can just lower the starting value from 1024 down to a lower number.

**Comment by s0nea** [comment]
Yes, right. If I assign two values to the setting, the second will just overwrite the first one.

**Comment by Nino-K** [comment]
> We should also document port 443 since traefik also listens on that port.

Right, I'm not saying to run `ip_unprivileged_port_start` again with port `443`. I'm just saying to include port `443` in the documentation so people won't get confused or something. My comment was mainly for documentation folks. Something  like:
Running the command `sudo sysctl -w net.ipv4.ip_unprivileged_port_start=80` allows traefik to listen on both port `80` and `443` on the host...

**Comment by s0nea** [comment]
Ah, yes, that's a good idea. Thank you! I misunderstood your previous comment.
