### ISSUE TITLE
1.8.0 Windows Screenshots

### ISSUE THREAD

**Issue by adamkpickering** [rancher-sandbox/docs.rancherdesktop.io#159]
Screenshots are here: [output.zip](https://github.com/rancher-sandbox/docs.rancherdesktop.io/files/10934960/output.zip)

**Comment by gunamata** [comment]
CC: @sunilarjun @nunix

**Comment by nunix** [comment]
The screenshots have been uploaded to S3 and the v1.8 docs PR has been updated.
