### ISSUE TITLE
rdctl reference is out-of-date

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/docs.rancherdesktop.io#172]
The warning at the top that the app needs to be running for `rdctl` to work is incomplete. Some subcommands, like `rdctl start` and `rdctl factory-reset` work by themselves.

The lists of available subcommands, or options (especially for `rdctl start` and `rdctl set`) seems very out-of-date.

**Comment by sunilarjun** [comment]
Closing issue as script was created to keep `rdctl` commands current, thank you
https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/174
