### ISSUE TITLE
The Search function should only search the docs for the currently selected version

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/docs.rancherdesktop.io#188]
Right now it returns results for each version, and the display doesn't even indicate which version each result comes from:

<img width="534" alt="CleanShot 2023-04-11 at 09 58 10@2x" src="https://user-images.githubusercontent.com/78947/231254676-381648b8-a445-4ca5-947a-28ed0efc8dda.png">

**Comment by gaktive** [comment]
@gunamata indicated that there's a request to have Agolia enabled on our repo.
