### ISSUE TITLE
Some section links in the Preferences tab are wrong

### ISSUE THREAD

**Issue by torchiaf** [rancher-sandbox/docs.rancherdesktop.io#215]
The links to the Application sub-tabs in the Preferences page have a number at the end,  instead of the pure section id.
This causes a mismatch with the Help buttons link in Rancher Desktop.

Example:

The 'Environment' link is `https://docs.rancherdesktop.io/next/ui/preferences/application/#environment-1`

![image](https://github.com/rancher-sandbox/docs.rancherdesktop.io/assets/26394656/d5e4ca7f-dd7a-4ad0-b0fe-df1b25908790)

**Comment by sunilarjun** [comment]
PR was merged fixing the links issue, closing this item, thank you.
