### ISSUE TITLE
We need more info on mouting volumes to VMs

### ISSUE THREAD

**Issue by ericpromislow** [rancher-sandbox/docs.rancherdesktop.io#23]
Lima & WSL both pre-mount volumes, but someone asked on slack:

Question was: 
```
Is filesharing working same like Docker Desktop?  I am using rancher desktop and i would like volume my local directiores? Do I have to configure anything on rancher desktop?
```

**Comment by MPParsley** [comment]
Docker desktop mounts /Volumes on Mac, when moving to Rancher desktop this can result in inaccessible volumes or empty file shares.

```
mounts:
  - location: /Users/user/Library/Caches/rancher-desktop/k3s
    writable: false
  - location: "~"
    writable: true
  - location: /tmp/rancher-desktop
    writable: true
>  - location: "/Volumes"
>    writable: true
```

**Comment by jandubois** [comment]
Just for reference (from the [Docker Desktop for Mac user manual](https://docs.docker.com/desktop/mac/#resources)).

> By default the `/Users`, `/Volume`, `/private`, `/tmp` and `/var/folders` directory are shared. 

On Windows all files are automatically shared via WSL2.
