### ISSUE TITLE
How-to guide: odo and Rancher Desktop

### ISSUE THREAD

**Issue by valaparthvi** [rancher-sandbox/docs.rancherdesktop.io#255]
While reading the tutorial on Skaffold and Rancher Desktop, it occurred to me that a similar doc could be written for [odo](https://github.com/redhat-developer/odo. `odo` is also a CLI developer tool to run applications on cluster and podman. It uses [devfile.yaml](https//devfile.io) configuration file.

Even though the working on skaffold and odo are similar, I think it would be interesting to add the article to the list.

Here's a [nodejs quickstart](https://odo.dev/docs/user-guides/quickstart/nodejs) for odo.

**Comment by sunilarjun** [comment]
Closing as #258 is merged into RD docs `next` version and will go into the latest `1.10` version upon release, thank you!
