### ISSUE TITLE
Basic workflow documentation

### ISSUE THREAD

**Issue by danielhelfand** [rancher-sandbox/docs.rancherdesktop.io#26]
When viewing the rancher desktop docs, it would be helpful to have a walkthrough which describes how to launch, stop, and delete a Kubernetes cluster. As a minikube user who is new to using a UI for working with a local cluster, it was not instantly intuitive on what the typical workflow for using rancher desktop was. 

Luckily, rancher desktop has a pretty nice UX, and, after poking around a bit, it was pretty simple to understand the basic workflow (i.e. Launch rancher desktop, select k8s version, and quit rancher desktop to stop the cluster or reset the cluster to delete/restore the cluster). Including pictures of the desktop UI to accompany this flow would be helpful as well.

Thanks for all the work on rancher desktop! Looking forward to your thoughts.

**Comment by gunamata** [comment]
Thank you for your feedback. At the moment, we are focusing on adding a bunch of docs and will cover this aspect as part of one of the Getting Started docs.

**Comment by danielhelfand** [comment]
Thanks for the update! Sounds good to me.
