### ISSUE TITLE
RD 1.10 Screenshots: Preferences & UI (macOS, Linux, and Windows)

### ISSUE THREAD

**Issue by sunilarjun** [rancher-sandbox/docs.rancherdesktop.io#268]
Creating issue to track files for Rancher Desktop 1.10 screenshot images wrt ~~macOS~~, ~~Linux~~, and Windows platforms.

**Comment by gunamata** [comment]
@adamkpickering to try generate for Linux
@jandubois  for macOS
@mook-as  for Windows

**Comment by sunilarjun** [comment]
Hello all! I had a drive shared with me from Tatjana containing macOS and Linux images, so just need the Windows screenshots. Thank you!

**Comment by sunilarjun** [comment]
Closing issue as macOS/Linux/Windows screenshots have been collected and uploaded to the `suse-rancher-media` S3 bucket, thanks all!
