### ISSUE TITLE
Heading on Emulation page should be on top of their screenshots, not after

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/docs.rancherdesktop.io#284]
Right now they are below their screenshots, which is confusing:

![CleanShot 2023-09-19 at 08 44 05@2x](https://github.com/rancher-sandbox/docs.rancherdesktop.io/assets/78947/cc96a12c-7a47-4bdb-accb-63af4127397a)

**Comment by sunilarjun** [comment]
Fixed by #286
