### ISSUE TITLE
Use proper location for apt gpg keys `/etc/apt/keyrings/`

### ISSUE THREAD

**Issue by julian-alarcon** [rancher-sandbox/docs.rancherdesktop.io#365]
Documentation currently sets the directory `/usr/share/keyrings` to store the gpg keys needed by apt installation.

As a best practice as this key will be only used by apt, the proper directory to store the gpg keys is `/etc/apt/keyrings/` refering to the specific scope for apt repositories.

**Comment by jandubois** [comment]
Thank you for opening the issue, but I can't find any documentation that specifically says where the keys should be installed, so I checked a current image:

```console
# cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
# ls /etc/apt/keyrings/
# ls /usr/share/keyrings/
debian-archive-bookworm-automatic.gpg		debian-archive-buster-automatic.gpg
debian-archive-bookworm-security-automatic.gpg	debian-archive-buster-security-automatic.gpg
debian-archive-bookworm-stable.gpg		debian-archive-buster-stable.gpg
debian-archive-bullseye-automatic.gpg		debian-archive-keyring.gpg
debian-archive-bullseye-security-automatic.gpg	debian-archive-removed-keys.gpg
debian-archive-bullseye-stable.gpg
```

So it looks like the keys are installed into `/usr/share` by default. So unless this changes I think we'll keep the docs as-is.

**Comment by julian-alarcon** [comment]
Documentation related to this is here:
https://wiki.debian.org/DebianRepository/UseThirdParty

> If future updates to the certificate will be managed by an apt/dpkg package as recommended below, then it SHOULD be downloaded into /usr/share/keyrings using the same filename that will be provided by the package. If it will be managed locally , it SHOULD be downloaded into /etc/apt/keyrings instead.

> In releases older than Debian 12 and Ubuntu 22.04, /etc/apt/keyrings does not exist by default. It SHOULD be created with permissions 0755 if it is needed and does not already exist. 

![image](https://github.com/user-attachments/assets/a8f98ab7-4906-400c-9d89-a5f2bc6971d5)

I feel that the case for the documentation as it's manually handled should be /etc/apt/keyrings/
