### ISSUE TITLE
Screenshots have no border and no shadows

### ISSUE THREAD

**Issue by jandubois** [rancher-sandbox/docs.rancherdesktop.io#384]
Shadows were supposed to be created via CSS in #138, but that either got lost or broken.

Right now screenshots just blend in with the background without any visible border:

<img width="839" alt="CleanShot 2024-07-31 at 11 25 20@2x" src="https://github.com/user-attachments/assets/c8b77dd0-394b-4701-bbe9-53beced8c292">

**Comment by mook-as** [comment]
#138 added:
https://github.com/rancher-sandbox/docs.rancherdesktop.io/blob/365822f9bcbb41b966ae75929d23beccfc63e1fb/src/css/custom.css#L33

However, the current class is `.img_CujE`.

**Comment by jandubois** [comment]
> However, the current class is `.img_CujE`.

@gunamata @sunilarjun Do you know where the classname comes from? We can obviously just change it right now, but I worry that it might change again in the future. Does it depend on the Docusaurus version? Is there a way to fix it instead of having a randomly generated name?

**Comment by mook-as** [comment]
We can always do `img[class^="img_"]` if we want… :p

I think it comes from react doing some sort of hashing, though, so it wouldn't be consistent.

**Comment by jandubois** [comment]
> We can always do `img[class^="img_"]` if we want… :p

Perfect! That's also what the Docusaurus docs recommend:

> **CSS module class names.** These class names have a hash in production (codeBlockContainer_RIuc) and are appended with a long file path in development. They are considered implementation details and you should almost always avoid targeting them in your custom CSS. If you must, you can use an [attribute selector](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) `([class*='codeBlockContainer'])` that ignores the hash.

(from https://docusaurus.io/docs/styling-layout)
