### ISSUE TITLE
missing a nice hello world example

### ISSUE THREAD

**Issue by do-m-en** [rancher-sandbox/docs.rancherdesktop.io#52]
Current documentation has a "Hello World" example for using nerdctl but for that I could just use docker...

From my point of view where Rancher Desktop comes into play is actually when you:
- develop application locally
- create container image locally (without pushing to a remote image repository)
- execute it in local kubernetes environment

I'm new to this kubernetes/rancher desktop/containers world so it took me a while to figure out how to execute above scenario on my own (and am not even certain that I used it correctly and not just accidentally found one of solutions that is not really the most elegant).

It'd be nice to have a hello world example that would:
- use command like: `nerdctl build -t <image_name>:local --namespace k8s.io -f <path_to>/Dockerfile .`
- show how you have to change kubernetes deployment script from remote repo:
```
image: <image_name>:latest
imagePullPolicy: Always
```
to local:
```
image: <image_url>:local
imagePullPolicy: Never
```

Add a **bold** note in `Working with Images` and `Features` (Images subsection) section that images from default namespace are not visible in kubernetes and have be forced into k8s.io namespace in order to be visible there. Current documentation only contains a cryptic somewhat hidden "oh and btw" in this segment:

> The initial set of images are stored in the same containerd that Kubernetes uses, and are part of the k8s.io namespace. You can also switch to a namespace called default if you wish to build or pull images into a different namespace.

Which requires you to read the whole thing to find out such an important "default is not actually what you want..." information and is actually misleading as it gives you the feeling that "k8s.io" is the default namespace while "default" is actually the default nerdctl namespace.
It's possible that this information is valid on a different OS - can't check - but I'm using Linux and there it doesn't work as described (or I misunderstood the text completely which is probably also a documentation issue).

Maybe it's possible that Deployment yaml can be namespaced so that it looks in "default" nerdctl namespace for known images but my knowledge of that is non-existent atm... If it is then this namespace interaction should probably also be documented as the issue remains: you have to force namespace somewhere (be it in nerdctl or in Deployment yaml file) to get the "works out of the box" experience for default Rancher Desktop usecase.

**Comment by gunamata** [comment]
Addressed in  https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/60
