### ISSUE TITLE
Installing docker-compose instructions do not appear to work/incomplete on linux

### ISSUE THREAD

**Issue by grahambunce** [rancher-sandbox/docs.rancherdesktop.io#66]
Full Linux: Ubuntu 20.04

Follow these instructions:

cd /tmp
mkdir dc-work
cd dc-work
curl -o docker-compose -kL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64
chmod +x docker-compose
mkdir -p ~/.docker/cli-plugins/
mv docker-compose ~/.docker/cli-plugins/
cd ..
rmdir dc-work

This line fails:
curl -o docker-compose -kL https://github.com/docker/compose/releases/download/v2.2.3/docker-compose-linux-x86_64

with
Warning: Failed to create the file docker-compose: Permission denied
curl: (23) Failure writing output to destination

Try with "sudo". Same error - checked github. File exists

I then tried to do this manually, i.e.

Go to the github website directly and download the file (same version). Copy file to dc-work and rename to "docker-compose".
continue as above from (and including) chmod +x docker-compose

Try to run docker-compose from command line, response:

```
Command 'docker-compose' not found, but can be installed with:

sudo snap install docker          # version 20.10.12, or
sudo apt  install docker-compose  # version 1.25.0-1

See 'snap info docker' for additional versions.
```

Are there any instructions missing (i.e. to create a link or something?)

FYI: I'm not a linux expert

I also mistakenly tried running the apt install docker-compose which then installed "full docker" locally instead of using my rancher version and lead to me needing to cleanup/remove docker/rancher and re-install rancher to get it all back to normal again

**Comment by jandubois** [comment]
With the just released 1.3.0 version of Rancher Desktop you should get docker-compose installed automatically. Can you please verify that?

In this case the documentation of how to install it manually can probably be removed instead.

**Comment by grahambunce** [comment]
@jandubois Thanks - I did the upgrade to 1.3 and docker-compose is recognised from the comment line. Thanks for this.

I will leave it to you to close or leave open as a trigger to update documentation.

**Comment by jandubois** [comment]
Thanks for confirming! I'll leave it open so somebody can update the docs to reflect the recent changes.

**Comment by gunamata** [comment]
Updated FAQ in this PR https://github.com/rancher-sandbox/docs.rancherdesktop.io/pull/67 related to docker-compose.
